### ISSUE TITLE
Alternative Mapping for Heatmaps

### ISSUE THREAD

**Issue by chebee7i** [marcharper/python-ternary#11]
Attached is crude plot of my understanding for how the heatmaps are calculated using triangular lattices. Essentially, each point is assigned to the lower-left corner of an upright triangle. The upside-down triangles are the averages of the upright triangles around them. 

This makes sense and is probably the easiest thing to do, but the result can be a bit counter intuitive in that a grid at scale `s` was put on the simplex while a grid at scale `s+1` is used for coloring. As an alternative, it might be nice to color each triangle to be the average of the points around it at the same scale (as shown in the bottom diagram). I might be able to tackle this in a week or so, but I thought I'd open an issue anyway.

![text5973](https://cloud.githubusercontent.com/assets/326005/8250396/e71d1a10-1638-11e5-8102-e5ab9bc0c2a8.png)

**Comment by marcharper** [comment]
Nice diagrams! Yes the current mapping is tuples to triangles rather than points. This was intentional for the original application since I needed to see from the heatmap exactly what was happening on the boundary.

This should be a relatively easy change -- there is already an iterator that computes the average value of the neighbors, so I would guess it can be adapted for this purpose

**Comment by chebee7i** [comment]
Ah yes, I can see how the current setup would be really helpful when the boundary is important (as it often is).

**Comment by marcharper** [comment]
I'll give this the old college try now that I'm thinking about it. I need names for the two different triangular heatmap styles, right now it's just "triangular" or "hexagonal". Any ideas?

**Comment by chebee7i** [comment]
It's tempting to think of the one which maps vertices to faces as "dual". That may or may not be informative to users though. Perhaps it is better for the name to give a sense for how the original points are represented.

A:   upright triangles in the heatmap are in a 1-1 correspondence with original vertices
B:   vertices of all triangles in the heatmap are in a 1-1 correspondence with the original vertices

Maybe: 

A: `triangular_center` : larger grid, with the original vertices appearing as triangle centers
B: `triangular_vertex`  : same size grid, with the original vertices appearing as triangle vertices

No matter the name, a picture will probably be the most helpful. Eventually, I can TikZ up something nice instead of these Inkscape hacks. Mentioning their use cases in the docstring is probably good too.

![path8433-0-7](https://cloud.githubusercontent.com/assets/326005/8258681/7d1cf8b2-167c-11e5-83aa-12844c2a9c72.png)

**Comment by marcharper** [comment]
OK I have a working implementation. 

![](http://i.imgur.com/tuzReJD.png)

I'll push a new branch later today (I'm busy for the next few hours), and hopefully we can test it a bit.

**Comment by marcharper** [comment]
@chebee7i Can you add your latest image (two posts up) to the images branch in the readme_images folder and submit a PR? I'd like to add it to the documentation (and give you credit).

**Comment by marcharper** [comment]
Ok, I pushed a new branch "alt-heatmap". It still needs a bit of work (I think I can refactor the heatmap function and it needs updated documentation), but it will plot the two styles above (correctly I think). I renamed the dual style to "dual-triangular" (or just "d") and the vertex-blending one just "triangular".

**Comment by chebee7i** [comment]
Sure thing. I'll render with TikZ and send a PR later today.

**Comment by chebee7i** [comment]
Opps...didn't get around to TikZing it. What are your thoughts on this picture? I'm wondering if we can get by without the arrows. It requires that you look back and forth between the colored triangle and the colorbar, but with proper prose, perhaps this is enough.But don't feel obligated to agree. If it doesn't convey the point clearly enough, I'm happy to put the effort into the doing this with TikZ. One advantage of this Python solution is that the source code can be included as well.

**Comment by marcharper** [comment]
This is nice. I do like the one with the arrows as well, but I'm biased since I already know how the various heatmaps work, so I'm probably not the best judge of which version is most clear to new people. We can include both images of course. Some thoughts:

- It's not necessary to TikZ the arrows images, it's fine as is
- The color version might be easier to understand if in black and white (or a single color)
- The hexagonal one is nice, it might benefit from being slightly larger so the full range of interior shapes is included
- Please include the generating code!
