### ISSUE TITLE
Removing first and last tick

### ISSUE THREAD

**Issue by taliaborofsky** [marcharper/python-ternary#167]
I wish there was a way to remove the ticks at the corners of a plot. For instance, in the plot below, it is confusing to see both 0 and 1 at a corner. However, it's understood that at the top corner, u_2 = 1, at the bottom left corner, \bar{u} = 1, and at the bottom right corner, u_1 = 1, and the presence of ticks at those corners is confusing.
![u_intern_K_0_D_0_beta_0_5_mu_neg0_5](https://user-images.githubusercontent.com/46119074/109741655-56f82500-7b82-11eb-8c1f-cf0cd19ad00c.png)

**Comment by marcharper** [comment]
Hi, it is possible to manually set the ticks using [this function](https://github.com/marcharper/python-ternary/blob/67a597e8e1b3c16ec06e819a5859c8a765ac2ce2/ternary/ternary_axes_subplot.py#L368). You can manually specify the tick values and locations explicitly.

Are you suggesting that there should be a convenience function to drop the ticks closest to the corners?

**Comment by taliaborofsky** [comment]
I didn't realize I could manually drop the ticks near the corners. But a convenience function would of course be nice.

**Comment by juanmvenegas** [comment]
I apologize for revisiting this issue, but it is unclear to me what format is needed in the tax.ticks method to drop specific ticks. Do we use a dictionary to specify the axes we want to include?

Using code like this to specify ticks between 0.1 and 0.9 (dropping 0.0 and 1.0):

```python
tax.ticks(axis='lbr', linewidth=1, multiple=0.1,tick_formats="%.1f",offset=0.02,ticks={"b":np.arange(0.1,0.9,0.1),
                                                                                       "l":np.arange(0.1,0.9,0.1),
                                                                                       "r":np.arange(0.1,0.9,0.1)})
```

Leads to the error:

```
  File ~\Miniconda3\envs\datasci\lib\site-packages\ternary\lines.py:287 in ticks
    tick = ticks[index]

KeyError: 0

```

Any feedback on the proper format would be appreciated.

**Comment by marcharper** [comment]
`ticks` has to be a [list not a dictionary](https://github.com/marcharper/python-ternary/blob/master/ternary/lines.py#L220) -- the function only supports setting multiple axes with the same ticks.

Since you want to leave off a value rather than just swap out values, you'll need to specify both `locations` and `ticks` explicitly. If you are dropping the same location / value (e.g. the first) on the same scale, then maybe you can call the function once (but still with a list, not a dict), otherwise you'll need to call it with the different locations and ticks for each axis individually.
