### ISSUE TITLE
ternary does not seem to use third axis value when plotting lines

### ISSUE THREAD

**Issue by dmalzl** [marcharper/python-ternary#187]
I am using ternary to plot some data with three different features. I was able to generate the plot and now wanted to add some boundary indications between groups using the following code:

```python
for tax, title in [tax1, tax2]:
    mid = [1/3] * 3
    for p in [
        [1, 0, 0], [0, 1, 0], [0, 0, 1], 
        [0.5, 0, 0], [0, 0.5, 0], [0, 0, 0.5]
    ]:
        tax.line(
            p, mid, ls = '--', c = 'lightgrey', zorder = 1
        )
```
However, except for the (0, 0, 1) the function does not seem to be able to plot any line between any (0, 0, x) (where x in [0, 1)). Furthermore, plotting a line between (0, y, x) results in a line between axis 2 and the midpoint which is even more odd.
Is this a bug or am I using it wrong?

**Comment by fairliereese** [comment]
This is because this implementation assumes that the sum of any three points in the simplex will sum to a constant (which should be your scale). Assuming your scale is 1, the points (0.5, 0, 0), (0, 0.5, 0), and (0, 0, 0.5) do not even exist. Check out [this discussion](https://github.com/marcharper/python-ternary/issues/140#issuecomment-646149514).

**Comment by dmalzl** [comment]
Thanks for the explanation. I see and to be honest I already suspected this. The only thing that puzzles me is why the (0.5, 0, 0) and (0, 0.5, 0) work and (0, 0, 0.5) does not. Anyway, I will have a look at the discussion then. Thanks again

**Comment by dmalzl** [comment]
The discussion helped. Tamed it. Thanks for the suggestion and sorry for being so mathematically illiterate :)
