### ISSUE TITLE
Bug in ticks()

### ISSUE THREAD

**Issue by CorySimon** [marcharper/python-ternary#38]
In `lines.py`, I think there is a bug, where it is assumed that `ticks` is a boolean, but I think it is either `None` or a list/array. Thus, I think we should change it to below. I got an error when I passed custom ticks to this function because of these, and it works now with this change. 

```
@@ -224,13 +224,13 @@ def ticks(ax, scale, ticks=None, locations=None, multiple=1, axis='b',
     if not axis_chars.issubset(valid_axis_chars):
         raise ValueError("axis must be some combination of 'l', 'r', and 'b'")
 
-    if ticks and not locations:
+    if ticks is not None and locations is None:
         num_ticks = len(ticks)
         if num_ticks != 0:
             multiple = scale / (num_ticks - 1)
             locations = arange(0, scale + multiple, multiple)
 
-    if not ticks:
+    if ticks is None:
         locations = arange(0, scale + multiple, multiple)
         ticks = locations

```

UPDATE: Also, I didn't take the time to understand why you need `ticks` and `locations`. Could we just remove the `locations` and use only `ticks=None` for default ticks, `ticks=[]` for no ticks and `ticks=arange(23)` for example, for custom ticks.

**Comment by marcharper** [comment]
Can you post the code that triggers the issue? In python `ticks` will be `False` if `ticks` is empty `[]` or `None`, so I'm not sure that it's necessary to check if `ticks is None` versus `not ticks`. In any case I'd like to see what you passed in so that the issue can be fixed.

Locations is necessary because `ternary` does not know if you want to use equally spaced ticks or not, and this behavior is assumed if `locations` is not supplied. Also, I think that it would be confusing if `ticks=None` and `ticks=[]` had different behaviors -- the reason that `ticks=None` renders something is because `multiple` has a non-zero default value. I'm not trying to get in the users head, and the following behaviors seem sufficient to me:

* Don't call `tax.ticks()` if you don't want any ticks
* Supply `tax.ticks(ticks=[...])` if you want custom values to be equally spaced out. Of course you could just change the value of `multiple` for most such cases. If `ticks=[]` or `None` then fall back to equally spaced ticks based on `multiple` and `scale`. I assume that if the user calls `tax.ticks()` they want something to render.
* Supply both `ticks` and their `locations` to allow whatever the user could possibly want
