### ISSUE TITLE
Not able to remove frame

### ISSUE THREAD

**Issue by Anthony-MostlyHarmless** [marcharper/python-ternary#39]
Hello,

I have tried to remove the frame with 

`frameon = False`

But nothing changed, any ideas ?

**Comment by marcharper** [comment]
Hi @Anthony-MostlyHarmless , to what function did you pass this parameter?

**Comment by marcharper** [comment]
I think this is a [matplotlib concern](http://stackoverflow.com/questions/14908576/how-to-remove-frame-from-matplotlib-pyplot-figure-vs-matplotlib-figure-frame), see the link for more information -- you can obtain the underlying mpl figure and axis references as follows:
```
fig, tax = ternary.figure()
ax = tax.get_axes() # or just tax.ax
```
and then do something like:
```
fig.patch.set_visible(False)
ax.axis('off')
```

I'll consider adding a pass-through argument to `ternary.figure`, but I'm hesitant to pass-through all `*args, **kwargs` since `ternary.figure` has some of its own arguments already.

**Comment by Anthony-MostlyHarmless** [comment]
It works, thanks a lot :)
