### ISSUE TITLE
Ternary.figure() - AttributeError: 'module' object has no attribute 'figure'

### ISSUE THREAD

**Issue by BJEBN** [marcharper/python-ternary#45]
Hi,

I have the following error when using 

`import ternary`
`ternary.figure()`

`Traceback (most recent call last):`
`File "<stdin>", line 1, in <module>`
`AttributeError: 'module' object has no attribute 'figure'
`

I am running Windows 7 and have tried to install the python-ternary module on several different python versions (none are registered in systems environments to ensure that it doesnt break ArcGIS python version). 

First I tried the command on two versions of Python 2.7.8 related to ArcGIS (32 & 64bit) 

Then i've tried in relation to different Anaconda versions

Anaconda3-4.0.0-Windows-x86.exe  (Python 3.5.1)
Anaconda3-4.0.0-Windows-x86_64.exe (Python 3.5.1)
Anaconda2-4.0.0-Windows-x86.exe (Python 2.7.11)
Anaconda2-4.0.0-Windows-x86_64.exe (Python 2.7.11)

All reproduce the same error message...

**Comment by marcharper** [comment]
Thanks. Based on our gitter conversation I'm guessing that at some point you did not have this issue? I'm trying to pinpoint if there was a specific change or commit that caused the issue. Also:

* If you run python from the `python-ternary` directory do you still have the error?
* What version of matplotlib is installed?

I suspect this is a packaging/windows issue since I'm not able to reproduce with anaconda on Ubuntu. If you look at the last line of [__init__.py](https://github.com/marcharper/python-ternary/blob/master/ternary/__init__.py) you can see that `figure` is explicitly imported. So it's there, and `import ternary` doesn't throw an exception, we just need to figure out why.

Also, if you have multiple versions of python on your system, you may need to specific the full path to python during the install command. In other words instead of
```
python setup.py install
```
try
```
C:\full_path\to\anaconda\python setup.py install
```

**Comment by BJEBN** [comment]
Yes I had ternary working perhaps 1 1/2 weeks ago before I had some Path problems between ArcGIS python and anaconda (had to reinstall everything)

I noticed that when I run pip uninstall ternary that it only removes the files

c:\anaconda2\lib\site-packages\setup.py
c:\anaconda2\lib\site-packages\setup.pyc
c:\anaconda2\lib\site-packages\ternary-0.1.dist-info\description.rst
c:\anaconda2\lib\site-packages\ternary-0.1.dist-info\installer
c:\anaconda2\lib\site-packages\ternary-0.1.dist-info\metadata
c:\anaconda2\lib\site-packages\ternary-0.1.dist-info\metadata.json
c:\anaconda2\lib\site-packages\ternary-0.1.dist-info\record
c:\anaconda2\lib\site-packages\ternary-0.1.dist-info\top_level.txt
c:\anaconda2\lib\site-packages\ternary-0.1.dist-info\wheel
c:\anaconda2\lib\site-packages\ternary.py
c:\anaconda2\lib\site-packages\ternary.pyc

Running 

`c:\Anaconda2>python.exe C:\Users\install\Downloads\python-ternary-master\python-
ternary-master\setup.py install`

`Traceback (most recent call last):`
 `File "C:\Users\install\Downloads\python-ternary-master\python-ternary-master\s
etup.py", line 4, in <module>`
    `with open('README.txt') as file:`
`IOError: [Errno 2] No such file or directory: 'README.txt'`

**Comment by BJEBN** [comment]
I have solved the issue by simply copying the ternary folder into the site-packages location of Anaconda. There appears to be an issue with the setup.py installation. I do not know if this only occurs on my system.

**Comment by marcharper** [comment]
Great, I'll leave it open for a few days in case this is an issue for anyone else.
