### ISSUE TITLE
Incorrect projection in main example

### ISSUE THREAD

**Issue by altosaar** [marcharper/python-ternary#90]
In the example for drawing arbitrary lines in this notebook: https://github.com/marcharper/python-ternary/blob/master/examples/Ternary-Examples.ipynb

```
# Draw an arbitrary line, ternary will project the points for you
p1 = (12,8,10)
p2 = (2, 26, 2)
tax.line(p1, p2, linewidth=3., marker='s', color='green', linestyle=":")
```

The point `p2 = (2, 26, 2)` is clearly not at the right location in the ensuing plot:

![image](https://user-images.githubusercontent.com/5317244/46099581-2764b780-c195-11e8-9bfd-8f7413c6d4b5.png)

Instead, it looks like the point is `p2 = (2, 26, 13)`. 

Am I missing something or is it incorrect?

**Comment by marcharper** [comment]
The library [ignores the third coordinate by default when projecting](https://github.com/marcharper/python-ternary/blob/master/ternary/helpers.py#L87) since there are only [two degrees of freedom](https://en.wikipedia.org/wiki/Ternary_plot) in a 2 dimensional plot. There's also [more than one way to interpret a coordinate](https://github.com/marcharper/python-ternary#axes-ticks-and-orientations).

There are a few [tests](https://github.com/marcharper/python-ternary/blob/master/tests/test_helpers.py#L61) that verify that the projection produces the expected values. If you can give an example where to projected point has the incorrect values please re-open the bug.

**Comment by MarkWieczorek** [comment]
Could you please

1. state clearly in the documentation that the third coordinate is irrelevant, and is equal to `scale - x - y`? A priori, if one coordinate is ignored, the user might like to know which one it is!
2. provide a check (perhaps optional) that the three coordinates sum to "scale".

Thanks,

**Comment by marcharper** [comment]
1. It is explained in the heatmap section that only the first two coordinates need to be supplied because the third is inferred. No one else has every asked about this so I don't think it's particularly unclear, but I welcome any PRs that improve the documentation. I will update the coordinates in the examples though since they changed from scale = 30 to 40 at some point.

2. No, this is a plotting library, not a data validation library. Someone may want to plot a point outside the simplex for all I know so why restrict that? Also if the coordinates are floats they may not sum exactly to `scale` and it's not clear how much error to allow.

**Comment by marcharper** [comment]
1. The default is to ignore the 3rd coordinate, it's possible to specific a different permutation so that a different coordinate is ignored. I'll think about it. Feel free to open a PR to update the documentation.

2. There may be good reasons that the values don't sum to `scale` exactly (rounding error, purposely adding a point outside the simplex, maybe others).
